### ISSUE TITLE
"Root element is missing" on auth StreamParser

### ISSUE THREAD

**Issue by i8beef** [pgstath/Sharp.Xmpp#35]
Ok, this is a little different and if I'm too far out of spec for this library that's fine. Hoping someone might be able to point me to what I'm doing wrong.

I'm playing with communicating with a Logitech Harmony Hub. It runs an XMPP server on 5222 on the device. There is some preamble auth ticket negotiation done before the actual login attempt through XMPP, which I have working ok, but when I attempt to actually connect, I'm getting an XmppException, with an inner exception coming from the StreamParser during the login attempt, from the XmlStreamReader of "Root element is missing.".

Login type should be XMPP SASL PLAIN.

Basics of what I'm attempting to recreate are here: https://github.com/jterrace/pyharmony/blob/master/PROTOCOL.md

```
using (var authClient = new XmppCore(ip, "guest@x.com", "guest", 5222, false))
{
    authClient.Connect();
}
```

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Sharp.Xmpp.Core.StreamParser.ReadRootElement()
   at Sharp.Xmpp.Core.StreamParser..ctor(Stream stream, Boolean leaveOpen)
   at Sharp.Xmpp.Core.XmppCore.InitiateStream(String hostname)
   at Sharp.Xmpp.Core.XmppCore.Authenticate(IEnumerable`1 mechanisms, String username, String password, String hostname)
   at Sharp.Xmpp.Core.XmppCore.SetupConnection(String resource)
   at Sharp.Xmpp.Core.XmppCore.Connect(String resource)

**Comment by jpenny1993** [comment]
Granted that you don't want a roster and want to access IqRequest functionality your example looks fine.

The XmlReader in ReadRootElement() doesn't seem to be able to read whats in the stream. Maybe try putting a breakpoint around there and have a look at whats in the stream object at that point.

**Comment by i8beef** [comment]
So following through the logic here, it looks like the code here is:

1. Opening a new STREAM (<stream:stream>)
2. Establishes an auth method from the return features from the server
3. Sends an authenticate message (<auth>)
4. Validates the signature, if any
5. Initiates a new stream (XmppCore line 1018) WITHOUT closing the first stream.

That doesn't seem right to me... When I do that in a console app, it immediately kicks me out.

**Comment by jpenny1993** [comment]
Yeah, It's not right. 
I knew the library dropped the initial connection when the logon method is called; this is because it was easier to reconnect with credentials then to authentication handshake separately.
I didn't realise it would do it if you've given the ctor it credentials.
I personally threw a trycatch around the authenticate method so I could do my stuff. I'll take a look at it when it's not 11pm, and if I make a pull request it might not make it in straight away. 

It could be worth you forking the project and helping fix it if you're definitely sticking with this library. Although I'd suggest checking out first [ubiety/xmpp](https://github.com/ubiety/xmpp) if you haven't yet.
