### ISSUE TITLE
Xamarin Integration Error

### ISSUE THREAD

**Issue by anandjitbanerjee** [pgstath/Sharp.Xmpp#61]
I am trying to integrate this for Xamarin android.Getting the following error.

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Drawing.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	OpenFire**

**Comment by Rychard** [comment]
[Mono for Android does not contain a `System.Drawing` assembly.](https://forums.xamarin.com/discussion/7124/system-drawing-dll-error)
